/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nombreusuario;

//Gaby
//gaby2

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.GridLayout;
import javax.swing.JPanel;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.BoxLayout;
import javax.swing.Icon;
import javax.swing.JFrame;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.Timer;



/**
 *
 * @author kenet
 */
public class Player1 extends javax.swing.JFrame {
    

   
    private static Boolean[][] estadoJuego = new Boolean[10][10];
    boolean[][] celdasR2 = new boolean[10][10];
    private EsperaTurno esperar = new EsperaTurno();;
    static boolean BarcosGuardados = false;
    static boolean ejecutado = false;
    public Player1() {

        
        initComponents();
        
        if (!BarcosGuardados) {
            GuardarPosicionesBarcos(CuadroBarcos);
            CoordenadasP1.setVisible(false);
            MensajeCoordenadasP1.setVisible(false);
            BarcosGuardados = true; // Marcamos las posiciones de los barcos como ya guardadas
        } else {
            coordenadas_de_Ataque_y_vida(CuadroBarcos, CoordenadasP1);
            Confirmar.setVisible(true);
            ConfirmarP.setVisible(true);

            if (!ejecutado) { // Verifica si PosicionBarcos ya se ha ejecutado
                for (int i = 1; i <= 9; i++) {
                    for (int j = 1; j <= 9; j++) {
                        celdasR2[j][i] = Player2.redcells2[j][i];
                    }
                }
                ejecutado = true; // Marca PosicionBarcos como ejecutado
            }
        }

        Confirmar.setVisible(false);
        ConfirmarP.setVisible(false);
       
    }
    
    public void hideFrame() {
        this.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Juego = new javax.swing.JPanel();
        CuadroBarcos = new FondoPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ConfirmarP = new javax.swing.JPanel();
        Confirmar = new javax.swing.JLabel();
        MensajeCoordenadasP1 = new javax.swing.JLabel();
        CoordenadasP1 = new javax.swing.JTextField();
        Mensaje_Error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        Juego.setBackground(new java.awt.Color(255, 255, 255));
        Juego.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout CuadroBarcosLayout = new javax.swing.GroupLayout(CuadroBarcos);
        CuadroBarcos.setLayout(CuadroBarcosLayout);
        CuadroBarcosLayout.setHorizontalGroup(
            CuadroBarcosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );
        CuadroBarcosLayout.setVerticalGroup(
            CuadroBarcosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );

        Juego.add(CuadroBarcos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 405, 405));

        jLabel4.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("9");
        Juego.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 45, 45));

        jLabel6.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("2");
        Juego.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 30, 45, 45));

        jLabel7.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("3");
        Juego.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 45, 45));

        jLabel8.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("4");
        Juego.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 30, 45, 45));

        jLabel9.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("5");
        Juego.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 45, 45));

        jLabel10.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("6");
        Juego.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 30, 45, 45));

        jLabel11.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("7");
        Juego.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 45, 45));

        jLabel12.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("8");
        Juego.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 30, 45, 45));

        jLabel13.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("1");
        Juego.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 45, 45));

        jLabel14.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("I");
        Juego.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 45, 45));

        jLabel15.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("A");
        Juego.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 45, 45));

        jLabel16.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("B");
        Juego.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 115, 45, 45));

        jLabel17.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("C");
        Juego.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 45, 45));

        jLabel18.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("D");
        Juego.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 205, 45, 45));

        jLabel19.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("E");
        Juego.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 45, 45));

        jLabel20.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("F");
        Juego.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 295, 45, 45));

        jLabel21.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("G");
        Juego.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 45, 45));

        jLabel22.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("H");
        Juego.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 385, 45, 45));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Capitan1.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        Juego.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 160, 200));

        ConfirmarP.setBackground(new java.awt.Color(0, 0, 0));

        Confirmar.setBackground(new java.awt.Color(255, 255, 255));
        Confirmar.setFont(new java.awt.Font("Roboto Light", 1, 16)); // NOI18N
        Confirmar.setForeground(new java.awt.Color(255, 255, 255));
        Confirmar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Confirmar.setText("CONFIRMAR");
        Confirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Confirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConfirmarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ConfirmarPLayout = new javax.swing.GroupLayout(ConfirmarP);
        ConfirmarP.setLayout(ConfirmarPLayout);
        ConfirmarPLayout.setHorizontalGroup(
            ConfirmarPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConfirmarPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ConfirmarPLayout.setVerticalGroup(
            ConfirmarPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConfirmarPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Juego.add(ConfirmarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 430, 100, 40));

        MensajeCoordenadasP1.setBackground(new java.awt.Color(0, 0, 0));
        MensajeCoordenadasP1.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        MensajeCoordenadasP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MensajeCoordenadasP1.setText("Ingrese coordenadas de ataque");
        Juego.add(MensajeCoordenadasP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 220, 20));

        CoordenadasP1.setForeground(new java.awt.Color(153, 153, 153));
        CoordenadasP1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CoordenadasP1.setText("A,1");
        CoordenadasP1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CoordenadasP1MouseClicked(evt);
            }
        });
        CoordenadasP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoordenadasP1ActionPerformed(evt);
            }
        });
        Juego.add(CoordenadasP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, 60, 30));

        Mensaje_Error.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        Mensaje_Error.setForeground(new java.awt.Color(255, 0, 0));
        Mensaje_Error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Juego.add(Mensaje_Error, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 160, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Juego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Juego, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   
    
   
    int saltar_turno = 0;    //Audio
    
    
    private void CoordenadasP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoordenadasP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CoordenadasP1ActionPerformed

    private void CoordenadasP1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CoordenadasP1MouseClicked
        
            if (CoordenadasP1.getText().equals("A,1")){
                CoordenadasP1.setFocusable(true);
                CoordenadasP1.requestFocusInWindow();
                CoordenadasP1.setText("");
                CoordenadasP1.setForeground(Color.black);
            }   
        
    }//GEN-LAST:event_CoordenadasP1MouseClicked

    
    private void ConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfirmarMouseClicked
  
        // In the confirmation button code:

        confirmedRectangles.add(new ArrayList<>(currentRectangle));
        for (Point p : currentRectangle) {
            clearLabels(labels, p.x, p.y);
        }
        currentRectangle.clear();
        for (List<Point> rectangle : confirmedRectangles) {
            for (Point p : rectangle) {
                if (labels[p.x][p.y] != null) {
                    labels[p.x][p.y].setOpaque(true);
                    labels[p.x][p.y].setBackground(Color.RED);
                }
            }
        }
        // Make the confirm button disappear
        Confirmar.setVisible(false);
        ConfirmarP.setVisible(false);

        // Check if there are any empty spaces in the matrix
        for (int i = 0; i < labels.length; i++) {
            for (int j = 0; j < labels[i].length; j++) {
                if (labels[i][j] != null && labels[i][j].getBackground() == Color.red) {
                    // El botón Confirmar debería reaparecer si hay un espacio vacío en la matriz
                    Confirmar.setVisible(true);
                    ConfirmarP.setVisible(true);
                    break;
                }

            }
        }

        saltar_turno++;
        rectanglesDrawn++;

        if (saltar_turno == 4){
            CoordenadasP1.setVisible(true);
            MensajeCoordenadasP1.setVisible(true);
            Confirmar.setVisible(false);
            ConfirmarP.setVisible(false);
            esperar.esperar();
            esperar.setVisible(true);
            this.setVisible(false);
        }
        
    }//GEN-LAST:event_ConfirmarMouseClicked

    public class FondoPanel extends JPanel {
    private Image imagen;
    //...
    @Override
    public void paint(Graphics g) {
        imagen = new ImageIcon(getClass().getResource("/IMAGENES/Mar.jpg")).getImage();
        g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
 
        setOpaque(false);
        super.paint(g);
        }
    //...
    }
   
/*int drawnRectanglesCount = 0;
int rectanglesDrawn = 0;
JLayeredPane Orden = new JLayeredPane();
int[] rectangleSizes = {2, 2, 3, 4};
int currentX = -1;
int currentY = -1;
JLabel[][] labels = new JLabel[10][10];
List<List<Point>> confirmedRectangles = new ArrayList<>();
List<Point> currentRectangle = new ArrayList<>();
boolean[][] celdasRojas1 = new boolean[10][10];

public void GuardarPosicionesBarcos(JPanel panel) {
    panel.setLayout(new GridLayout(9, 9));
    JLabel[][] labels = new JLabel[10][10];
    for (int i = 1; i <= 9; i++) {
        for (int j = 1; j <= 9; j++) {
            final int x = j;
            final int y = i;
            labels[j][i] = new JLabel();
            labels[j][i].setPreferredSize(new Dimension(45, 45));
            labels[j][i].setBorder(BorderFactory.createLineBorder(Color.WHITE));          
            labels[j][i].addMouseListener(new MouseAdapter() {
                boolean isVertical = false;
int direction = 0; // Agregamos una variable para rastrear la dirección del rectángulo

@Override
public void mouseClicked(MouseEvent e) {
    if (rectanglesDrawn >= rectangleSizes.length) return;
    System.out.println("Label presionado en la posición: (" + x + ", " + y + ")");
    
    int size = rectangleSizes[rectanglesDrawn];
    
    for (Point p : currentRectangle) {
        clearLabels(labels, p.x, p.y);
    }
    currentRectangle.clear();
    
    
    // Check if the new position is already occupied by a confirmed rectangle
    Confirmar.setVisible(true); 
    ConfirmarP.setVisible(true);
    boolean canDraw = false;
    for (int d = 0; d < 4; d++) { // Verificamos si el rectángulo se puede dibujar en cada una de las cuatro direcciones
        direction = (direction + 1) % 4; // Cambiamos la dirección cada vez que se verifica una nueva dirección
        canDraw = true;
        if (direction == 0 || direction == 2) { // Verificamos si la dirección es hacia la derecha o hacia la izquierda
            for (int i = 0; i < size; i++) {
                int newX = x + i;
                if (direction == 2) newX = x - i; // Si la dirección es hacia la izquierda, restamos en lugar de sumar
                if (newX > 9 || newX < 1) { // Si el nuevo valor de X está fuera de los límites, no dibujamos el rectángulo
                  
                    canDraw = false;
                    break;
                }
                for (List<Point> confirmedRectangle : confirmedRectangles) {
                    for (Point p : confirmedRectangle) {
                        if (p.x == newX && p.y == y) {
                            canDraw = false;
                            break;
                        }
                    }
                    if (!canDraw) break;
                }
            }
        } else { // La dirección es hacia arriba o hacia abajo
            for (int i = 0; i < size; i++) {
                int newY = y + i;
                if (direction == 3) newY = y - i; // Si la dirección es hacia arriba, restamos en lugar de sumar
                if (newY > 9 || newY < 1) { // Si el nuevo valor de Y está fuera de los límites, no dibujamos el rectángulo
                    canDraw = false;
                    break;
                }
                for (List<Point> confirmedRectangle : confirmedRectangles) {
                    for (Point p : confirmedRectangle) {
                        if (p.x == x && p.y == newY) {
                            canDraw = false;
                            break;
                        }
                    }
                    if (!canDraw) break;
                }
            }
        }
        if (canDraw) break; // Si encontramos una dirección en la que el rectángulo se puede dibujar, salimos del bucle
    }
    if (canDraw) {
        if (direction == 0 || direction == 2) { // Dibujamos el rectángulo hacia la derecha o hacia la izquierda
            for (int i = 0; i < size; i++) {
                int newX = x + i;
                if (direction == 2) newX = x - i; // Si la dirección es hacia la izquierda, restamos en lugar de sumar
                if (newX > 9 || newX < 1) continue; // Si el nuevo valor de X está fuera de los límites, no dibujamos esa celda
                if (labels[newX][y] != null) {
                    labels[newX][y].setOpaque(true);
                    labels[newX][y].setBackground(Color.RED);
                    celdasRojas1[newX][y] = true; 
                    
                    currentRectangle.add(new Point(newX, y));
                }
            }
        } else { // Dibujamos el rectángulo hacia arriba o hacia abajo
            for (int i = 0; i < size; i++) {
                int newY = y + i;
                if (direction == 3) newY = y - i; // Si la dirección es hacia arriba, restamos en lugar de sumar
                if (newY > 9 || newY < 1) continue; // Si el nuevo valor de Y está fuera de los límites, no dibujamos esa celda
                if (labels[x][newY] != null) {
                    labels[x][newY].setOpaque(true);
                    labels[x][newY].setBackground(Color.RED);
                    celdasRojas1[x][newY] = true; 
                    currentRectangle.add(new Point(x, newY));
                }
            }
        }
        redcells1 = new boolean[10][10];
        for (int i = 0; i < 10; i++) {
        for (int j = 0; j < 10; j++) {
            redcells1[i][j] = celdasRojas1[i][j];
        }
    }
    }
    
    currentX = x;
    currentY = y;
    
    
}
            });
            panel.add(labels[j][i]); 
            
        }
    }
}

public static boolean[][] redcells1;



public void clearLabels(JLabel[][] labels, int x, int y) {
    if (x >= 1 && x <= 9 && y >= 1 && y <= 9 && labels[x][y] != null) {
        labels[x][y].setOpaque(false);
        labels[x][y].setBackground(null);
        celdasRojas1[x][y] = false; 
    }
}*/
    
    int drawnRectanglesCount = 0;
int rectanglesDrawn = 0;
JLayeredPane Orden = new JLayeredPane();
int[] rectangleSizes = {2, 2, 3, 4};
int currentX = -1;
int currentY = -1;
JLabel[][] labels = new JLabel[10][10];
List<List<Point>> confirmedRectangles = new ArrayList<>();
List<Point> currentRectangle = new ArrayList<>();
boolean[][] celdasRojas1 = new boolean[10][10];

public void GuardarPosicionesBarcos(JPanel panel) {
    panel.setLayout(new GridLayout(9, 9));
    JLabel[][] labels = new JLabel[10][10];
    for (int i = 1; i <= 9; i++) {
        for (int j = 1; j <= 9; j++) {
            final int x = j;
            final int y = i;
            labels[j][i] = new JLabel();
            labels[j][i].setPreferredSize(new Dimension(45, 45));
            labels[j][i].setBorder(BorderFactory.createLineBorder(Color.WHITE));          
            labels[j][i].addMouseListener(new MouseAdapter() {
                boolean isVertical = false;
int direction = 0; // Agregamos una variable para rastrear la dirección del rectángulo

@Override
public void mouseClicked(MouseEvent e) {
    if (rectanglesDrawn >= rectangleSizes.length) return;
    System.out.println("Label presionado en la posición: (" + x + ", " + y + ")");
    
    int size = rectangleSizes[rectanglesDrawn];
    
    for (Point p : currentRectangle) {
        clearLabels(labels, p.x, p.y);
    }
    currentRectangle.clear();
    
    
    // Check if the new position is already occupied by a confirmed rectangle
    Confirmar.setVisible(true); 
    ConfirmarP.setVisible(true);
    boolean canDraw = false;
    for (int d = 0; d < 4; d++) { // Verificamos si el rectángulo se puede dibujar en cada una de las cuatro direcciones
        direction = (direction + 1) % 4; // Cambiamos la dirección cada vez que se verifica una nueva dirección
        canDraw = true;
        if (direction == 0 || direction == 2) { // Verificamos si la dirección es hacia la derecha o hacia la izquierda
            for (int i = 0; i < size; i++) {
                int newX = x + i;
                if (direction == 2) newX = x - i; // Si la dirección es hacia la izquierda, restamos en lugar de sumar
                if (newX > 9 || newX < 1) { // Si el nuevo valor de X está fuera de los límites, no dibujamos el rectángulo
                  
                    canDraw = false;
                    break;
                }
                for (List<Point> confirmedRectangle : confirmedRectangles) {
                    for (Point p : confirmedRectangle) {
                        if (p.x == newX && p.y == y) {
                            canDraw = false;
                            break;
                        }
                    }
                    if (!canDraw) break;
                }
            }
        } else { // La dirección es hacia arriba o hacia abajo
            for (int i = 0; i < size; i++) {
                int newY = y + i;
                if (direction == 3) newY = y - i; // Si la dirección es hacia arriba, restamos en lugar de sumar
                if (newY > 9 || newY < 1) { // Si el nuevo valor de Y está fuera de los límites, no dibujamos el rectángulo
                    canDraw = false;
                    break;
                }
                for (List<Point> confirmedRectangle : confirmedRectangles) {
                    for (Point p : confirmedRectangle) {
                        if (p.x == x && p.y == newY) {
                            canDraw = false;
                            break;
                        }
                    }
                    if (!canDraw) break;
                }
            }
        }
        if (canDraw) break; // Si encontramos una dirección en la que el rectángulo se puede dibujar, salimos del bucle
    }
    if (canDraw) {
        if (direction == 0 || direction == 2) { // Dibujamos el rectángulo hacia la derecha o hacia la izquierda
            for (int i = 0; i < size; i++) {
                int newX = x + i;
                if (direction == 2) newX = x - i; // Si la dirección es hacia la izquierda, restamos en lugar de sumar
                if (newX > 9 || newX < 1) continue; // Si el nuevo valor de X está fuera de los límites, no dibujamos esa celda
                if (labels[newX][y] != null) {
                    labels[newX][y].setOpaque(true);
                    labels[newX][y].setBackground(Color.RED);
                    celdasRojas1[newX][y] = true; 
                    
                    currentRectangle.add(new Point(newX, y));
                }
            }
        } else { // Dibujamos el rectángulo hacia arriba o hacia abajo
            for (int i = 0; i < size; i++) {
                int newY = y + i;
                if (direction == 3) newY = y - i; // Si la dirección es hacia arriba, restamos en lugar de sumar
                if (newY > 9 || newY < 1) continue; // Si el nuevo valor de Y está fuera de los límites, no dibujamos esa celda
                if (labels[x][newY] != null) {
                    labels[x][newY].setOpaque(true);
                    labels[x][newY].setBackground(Color.RED);
                    celdasRojas1[x][newY] = true; 
                    currentRectangle.add(new Point(x, newY));
                }
            }
        }
        redcells1 = new boolean[10][10];
        for (int i = 0; i < 10; i++) {
        for (int j = 0; j < 10; j++) {
            redcells1[i][j] = celdasRojas1[i][j];
        }
    }
    }
    
    currentX = x;
    currentY = y;
    
    
}
            });
            panel.add(labels[j][i]); 
            
        }
    }
}

public static boolean[][] redcells1;



public void clearLabels(JLabel[][] labels, int x, int y) {
    if (x >= 1 && x <= 9 && y >= 1 && y <= 9 && labels[x][y] != null) {
        labels[x][y].setOpaque(false);
        labels[x][y].setBackground(null);
        celdasRojas1[x][y] = false; 
    }
}
   

private Timer timer;
/*
public void AgregarPosicionesBarcos(JPanel panel, JTextField CoordenadasP1) {
    panel.setLayout(new GridLayout(9, 9));
    JLabel[][] labels = new JLabel[10][10];
    for (int i = 1; i <= 9; i++) {
    for (int j = 1; j <= 9; j++) {
        final int x = j;
        final int y = i;
        labels[j][i] = new JLabel();
        labels[j][i].setPreferredSize(new Dimension(45, 45));
        labels[j][i].setBorder(BorderFactory.createLineBorder(Color.WHITE));
        labels[j][i].setHorizontalAlignment(SwingConstants.CENTER);
        labels[j][i].setVerticalAlignment(SwingConstants.CENTER);
        labels[j][i].setFont(new Font("Roboto Black", Font.BOLD, 36));
        panel.add(labels[j][i]);
    }
}

    CoordenadasP1.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        String text = CoordenadasP1.getText();
        if (text.length() == 3 && text.charAt(1) == ',') {
            int y = text.toUpperCase().charAt(0) - 'A' + 1;
            int x = Character.getNumericValue(text.charAt(2));
            if (x >= 1 && x <= 9 && y >= 1 && y <= 9) {
                System.out.println("Label presionado en la posición: (" + x + ", " + y + ")");
                if (celdasR2[x][y]) {
                    labels[x][y].setText("O");
                    labels[x][y].setForeground(Color.RED);
                } else {
                    labels[x][y].setText("X");
                    labels[x][y].setForeground(Color.WHITE);
                }
                
                Timer timer = new Timer(2000, new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        esperar.esperar();
                        hideFrame();
                        esperar.setVisible(true);
                    }
                });
                timer.setRepeats(false);
                timer.start();
            }
            else{     
            Mensaje_Error.setText("Datos incorrectos!!");
            Mensaje_Error.setVisible(true);
            
            }
        }
    }
        });

}
*/



public void coordenadas_de_Ataque_y_vida(JPanel panel, JTextField CoordenadasP1) {
    panel.setLayout(new GridLayout(9, 9));
    JLabel[][] labels = new JLabel[10][10];
    for (int i = 1; i <= 9; i++) {
        for (int j = 1; j <= 9; j++) {
            final int x = j;
            final int y = i;
            labels[j][i] = new JLabel();
            labels[j][i].setPreferredSize(new Dimension(45, 45));
            labels[j][i].setBorder(BorderFactory.createLineBorder(Color.WHITE));
            labels[j][i].setHorizontalAlignment(SwingConstants.CENTER);
            labels[j][i].setVerticalAlignment(SwingConstants.CENTER);
            labels[j][i].setFont(new Font("Roboto Black", Font.BOLD, 36));
            panel.add(labels[j][i]);
        }
    }

    for (int i = 1; i <= 9; i++) {
        for (int j = 1; j <= 9; j++) {
            if (estadoJuego[j][i] != null) {
                if (estadoJuego[j][i]) {
                    labels[j][i].setText("O");
                    labels[j][i].setForeground(Color.RED);
                } else {
                    labels[j][i].setText("X");
                    labels[j][i].setForeground(Color.WHITE);
                }
            }
        }
    }

    CoordenadasP1.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            String text = CoordenadasP1.getText();
            if (text.length() == 3 && text.charAt(1) == ',') {
                int y = text.toUpperCase().charAt(0) - 'A' + 1;
                int x = Character.getNumericValue(text.charAt(2));
                if (x >= 1 && x <= 9 && y >= 1 && y <= 9 && labels[x][y].getText().isEmpty()) {
                    System.out.println("Label presionado en la posición: (" + x + ", " + y + ")");
                    if (celdasR2[x][y]) {
                        labels[x][y].setText("O");
                        labels[x][y].setForeground(Color.RED);
                        estadoJuego[x][y] = true;
                    } else {
                        labels[x][y].setText("X");
                        labels[x][y].setForeground(Color.WHITE);
                        estadoJuego[x][y] = false;
                    }

                    Timer timer = new Timer(1000, new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e) {
                            esperar.esperar();
                            hideFrame();
                            esperar.setVisible(true);
                        }
                    });
                    timer.setRepeats(false);
                    timer.start();
                } else {
                    Mensaje_Error.setText("Datos incorrectos!!");
                    Mensaje_Error.setVisible(true);
                }
            }
        }
    });
}







                                


       /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       //No se que hace pero me parece puede ser removido -- mientras lo comento
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Player1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Player1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Player1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Player1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
 
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            
                new Player1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Confirmar;
    private javax.swing.JPanel ConfirmarP;
    private javax.swing.JTextField CoordenadasP1;
    private javax.swing.JPanel CuadroBarcos;
    private javax.swing.JPanel Juego;
    private javax.swing.JLabel MensajeCoordenadasP1;
    private javax.swing.JLabel Mensaje_Error;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}